server:
  port: 8079

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pasteshare
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    dispatch-options-request: true
  graphql:
    cors:
      allowed-origins: http://localhost:3000
  flyway:
    baseline-on-migrate: true

logging:
  level:
    root: INFO

jwt:
  token:
    access:
      expiration: 3600
      secret: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    refresh:
      expiration: 86400
